name = "curl-converter"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

[env.production]
name = "curl-converter-prod"
routes = [
  { pattern = "diwas.pro", zone_name = "diwas.pro" }
]

[build]
command = "pnpm run build"
cwd = "./"
watch_paths = ["client/src/**/*.{ts,tsx,css}"]

[build.upload]
format = "service-worker"
main = "./dist/index.js"

[build.upload.rules]
type = "CompiledContentType"
globs = ["**/*.wasm"]
fallthrough = true

[[build.upload.rules]]
type = "Text"
globs = ["**/*.html"]
fallthrough = true

[[build.upload.rules]]
type = "Text"
globs = ["**/*.css"]
fallthrough = true

[[build.upload.rules]]
type = "Text"
globs = ["**/*.js"]
fallthrough = true

[[build.upload.rules]]
type = "Text"
globs = ["**/*.json"]
fallthrough = true

[[build.upload.rules]]
type = "Text"
globs = ["**/*.svg"]
fallthrough = true

[[build.upload.rules]]
type = "Text"
globs = ["**/*.xml"]
fallthrough = true

[[build.upload.rules]]
type = "Text"
globs = ["**/*.txt"]
fallthrough = true

[[build.upload.rules]]
type = "Text"
globs = ["**/*.md"]
fallthrough = true

[env.production.build]
command = "pnpm run build"
cwd = "./"
